import 'package:dart_jsonwebtoken/dart_jsonwebtoken.dart';

import '../errors.dart';
import '../models/entitlement.dart';

/// The RS256 public key bundled with the SDK.
///
/// This is the real public key generated by the SipKit licensing backend.
/// Providers may override it via [EntitlementVerifier] for key pinning
/// (e.g. after rotating the licensing server keypair).
///
/// To refresh after a key rotation, fetch:
///   GET https://your-sipkit-backend.com/api/v1/public-key
const _kDefaultPublicKeyPem = '''
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5GEXT56JvYEllu8wYiHx
TqdYBzs6JbOEL36crOov4jlvyXzPCcW7b2KZRAG9dIm0vKjB9EK2jDjhxoBoyTJ8
YUHl+s2/ayXdZbbaquItxviRirWR2tdbQ0HjIziomIlvBE1T93sNYWMQulqK1JJs
/4gF1IvEFaa3Hd9XiWjBB9xYIjUXQUoKefS01KUlHBIivXLKDEjSuwmVWl52xwDZ
641Cuj/2jYvY6YttL3ENVe7+aczJdJlHKGlZk+Ph74SIrMFbPUQ+WN3pNvLB8Xeu
Q/NtcjsQuE7tjHAJkVAIbjvEtjeUoUzAegPtEg2u7tTU/tA90HxPIbJDO+wv/f1y
GwIDAQAB
-----END PUBLIC KEY-----
''';

/// Verifies and decodes the entitlement JWT issued by the SipKit licensing
/// backend.  The token is signed RS256 and verified offline using the bundled
/// public key (or a provider-supplied override for key pinning).
class EntitlementVerifier {
  EntitlementVerifier({String? publicKeyPem})
      : _publicKey = RSAPublicKey(publicKeyPem ?? _kDefaultPublicKeyPem);

  final RSAPublicKey _publicKey;

  /// Verify [token] signature and return the decoded [Entitlement].
  ///
  /// Expiry is NOT hard-blocked here — the client applies the 72h grace window
  /// on top.  Only the issuer and signature are validated strictly.
  ///
  /// Throws [ActivationError] if the signature is invalid, the issuer is
  /// unexpected, or the token is structurally malformed.
  Entitlement verify(String token) {
    try {
      // checkExpiresIn: false — we handle expiry + grace separately.
      final jwt = JWT.verify(token, _publicKey, checkExpiresIn: false);
      final claims = jwt.payload as Map<String, dynamic>;

      if (claims['iss'] != 'sipkit-license') {
        throw const ActivationError(
            'Entitlement token has an unexpected issuer. '
            'Ensure you are pointing at a SipKit licensing backend.');
      }

      return Entitlement.fromClaims(claims);
    } on JWTInvalidException catch (e) {
      throw ActivationError('Entitlement token has an invalid signature: ${e.message}');
    } on JWTExpiredException {
      // Expired but valid signature — decode without expiry check for grace.
      return _decodeNoVerify(token) ??
          (throw const ActivationError('Entitlement token is expired and undecodable.'));
    } on JWTUndefinedException catch (e) {
      throw ActivationError('Entitlement token is malformed: ${e.message}');
    } catch (e) {
      if (e is ActivationError) rethrow;
      throw ActivationError('Failed to verify entitlement token: $e');
    }
  }

  /// Decode [token] without signature verification (for offline cache reads
  /// where we trust the local storage, not the network).
  /// Returns `null` if the token is structurally malformed.
  Entitlement? tryDecode(String token) => _decodeNoVerify(token);

  Entitlement? _decodeNoVerify(String token) {
    try {
      final jwt = JWT.decode(token);
      final claims = jwt.payload as Map<String, dynamic>;
      return Entitlement.fromClaims(claims);
    } catch (_) {
      return null;
    }
  }
}

/// Feature and limit checks against a decoded [Entitlement].
extension EntitlementChecks on Entitlement {
  /// Throws [NotEntitledError] if [feature] is not in [features].
  void requireFeature(String feature) {
    if (!hasFeature(feature)) {
      throw NotEntitledError(
          'The "$feature" feature is not enabled in your current entitlement. '
          'Contact your SipKit administrator to upgrade your license.');
    }
  }

  /// Throws [NotEntitledError] if [currentCount] is already at [maxAccounts].
  void requireAccountSlot(int currentCount) {
    if (currentCount >= maxAccounts) {
      throw NotEntitledError(
          'Account limit reached ($currentCount/$maxAccounts). '
          'Your entitlement allows up to $maxAccounts simultaneous accounts. '
          'Contact your SipKit administrator to increase your limit.');
    }
  }

  /// Throws [NotEntitledError] if [currentCount] is already at [maxConcurrentCalls].
  void requireCallSlot(int currentCount) {
    if (currentCount >= maxConcurrentCalls) {
      throw NotEntitledError(
          'Concurrent call limit reached ($currentCount/$maxConcurrentCalls). '
          'Your entitlement allows up to $maxConcurrentCalls concurrent calls.');
    }
  }
}
