#!/usr/bin/env bash
# Verify native artifacts produced by the pinned build scripts.
#
# This intentionally does not build anything. It is safe to run in CI after
# the platform-specific build jobs have uploaded their outputs.
set -euo pipefail

TOOL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_DIR="$(cd "$TOOL_DIR/.." && pwd)"
ANDROID_ARTIFACT="${ANDROID_ARTIFACT:-$PACKAGE_DIR/android/libs/pjsua2-2.14.aar}"
IOS_ARTIFACT="${IOS_ARTIFACT:-$PACKAGE_DIR/ios/Frameworks/PJSIP.xcframework}"
MODE="all"

usage() {
  cat <<'EOF'
Usage: verify_native_artifacts.sh [--android-only | --ios-only]

Verify the Android AAR and/or iOS XCFramework generated by the pinned native
build scripts. The default checks both artifacts.
EOF
}

die() {
  echo "error: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 ||
    die "missing prerequisite '$1'. $2"
}

has_entry() {
  local listing="$1"
  local entry="$2"
  grep -Fqx "$entry" <<<"$listing"
}

verify_android() {
  require_command unzip "Install unzip to inspect the AAR."
  require_command file "Install file to inspect native ELF architectures."
  [[ -f "$ANDROID_ARTIFACT" ]] ||
    die "Android artifact not found: $ANDROID_ARTIFACT"

  local listing
  listing="$(unzip -Z1 "$ANDROID_ARTIFACT")"
  for entry in \
    AndroidManifest.xml \
    classes.jar \
    META-INF/PJPROJECT-GPL-NOTICE.md \
    META-INF/GPL-2.0.txt \
    META-INF/OPENSSL-LICENSE.txt \
    jni/arm64-v8a/libpjsua2.so \
    jni/arm64-v8a/libc++_shared.so \
    jni/armeabi-v7a/libpjsua2.so \
    jni/armeabi-v7a/libc++_shared.so \
    jni/x86_64/libpjsua2.so \
    jni/x86_64/libc++_shared.so; do
    has_entry "$listing" "$entry" ||
      die "Android AAR is missing: $entry"
  done

  grep -Fq 'org/pjsip/pjsua2/' <<<"$listing" ||
    die "Android AAR contains no compiled org.pjsip.pjsua2 bindings."

  local unexpected
  unexpected="$(
    grep -E '^jni/(arm64-v8a|armeabi-v7a|x86_64)/.*\.so$' <<<"$listing" |
      grep -Ev '/(libpjsua2|libc\+\+_shared)\.so$' || true
  )"
  [[ -z "$unexpected" ]] ||
    die "Android AAR contains unexpected native shared libraries:\n$unexpected"

  echo "Android AAR: $ANDROID_ARTIFACT"
  local native_info
  for abi in arm64-v8a armeabi-v7a x86_64; do
    native_info="$(unzip -p "$ANDROID_ARTIFACT" "jni/$abi/libpjsua2.so" | file -)"
    case "$abi" in
      arm64-v8a)
        grep -Eqi 'aarch64|arm64' <<<"$native_info" ||
          die "$abi libpjsua2.so is not an ARM64 ELF: $native_info"
        ;;
      armeabi-v7a)
        grep -Eqi 'ARM' <<<"$native_info" ||
          die "$abi libpjsua2.so is not an ARM ELF: $native_info"
        ;;
      x86_64)
        grep -Eqi 'x86-64|x86_64' <<<"$native_info" ||
          die "$abi libpjsua2.so is not an x86_64 ELF: $native_info"
        ;;
    esac
    printf '  %-12s %s\n' "$abi" "$native_info"
  done
  echo "  bindings: org.pjsip.pjsua2 present"
  echo "  GPL/OpenSSL notices: present"
}

verify_ios() {
  require_command find "Install find to inspect the XCFramework."
  [[ -d "$IOS_ARTIFACT" ]] ||
    die "iOS artifact not found: $IOS_ARTIFACT"
  [[ -f "$IOS_ARTIFACT/Info.plist" ]] ||
    die "iOS XCFramework is missing Info.plist."
  [[ -f "$IOS_ARTIFACT/PJPROJECT-GPL-NOTICE.md" ]] ||
    die "iOS XCFramework is missing PJPROJECT-GPL-NOTICE.md."
  [[ -f "$IOS_ARTIFACT/GPL-2.0.txt" ]] ||
    die "iOS XCFramework is missing GPL-2.0.txt."

  local libraries
  libraries="$(
    find "$IOS_ARTIFACT" -type f \( -name PJSUA2 -o -name '*.a' \) -print
  )"
  [[ "$(wc -l <<<"$libraries")" -ge 2 ]] ||
    die "iOS XCFramework contains fewer than two library slices."
  local header
  header="$(find "$IOS_ARTIFACT" -type f -name '*.h' -print -quit)"
  [[ -n "$header" ]] ||
    die "iOS XCFramework contains no public headers."

  echo "iOS XCFramework: $IOS_ARTIFACT"
  while IFS= read -r library; do
    if command -v lipo >/dev/null 2>&1; then
      printf '  '
      lipo -info "$library"
    else
      echo "  library: $library"
    fi
  done <<<"$libraries"
  echo "  headers: present"
  echo "  GPL notices: present"
}

while (($#)); do
  case "$1" in
    --android-only) MODE="android" ;;
    --ios-only) MODE="ios" ;;
    -h|--help)
      usage
      exit 0
      ;;
    *) usage >&2; die "unknown option: $1" ;;
  esac
  shift
done

case "$MODE" in
  android) verify_android ;;
  ios) verify_ios ;;
  all)
    verify_android
    verify_ios
    ;;
esac

echo "Native artifact verification passed."