import 'dart:async';

import '../models/account_config.dart';
import '../models/account_status.dart';
import '../engine/sip_engine.dart';

/// A registered SIP account managed by [SipKitClient].
///
/// Obtain instances via [SipKitClient.addAccount] — do not construct directly.
class SipKitAccount {
  SipKitAccount._({
    required this.id,
    required this.config,
    required SipEngine engine,
  })  : _engine = engine,
        _statusCtrl = StreamController<AccountStatus>.broadcast() {
    _currentStatus = AccountStatus.unregistered;
  }

  /// Stable account identifier (UUID, generated by [SipKitClient]).
  final String id;

  /// The configuration supplied when this account was created.
  final SipKitAccountConfig config;

  final SipEngine _engine;
  final StreamController<AccountStatus> _statusCtrl;

  late AccountStatus _currentStatus;

  // ─── Public API ────────────────────────────────────────────────────────────

  /// Registration status broadcast stream.
  Stream<AccountStatus> get status => _statusCtrl.stream;

  /// Snapshot of the current [AccountStatus].
  AccountStatus get currentStatus => _currentStatus;

  /// Send a REGISTER request.  No-op if already [AccountStatus.registered].
  Future<void> register() async {
    if (_currentStatus == AccountStatus.registered) return;
    updateStatus(AccountStatus.registering);
    await _engine.registerAccount(id, config);
  }

  /// Send a REGISTER with `expires=0`.
  Future<void> unregister() async {
    await _engine.unregister(id);
  }

  // ─── Internal helpers ──────────────────────────────────────────────────────

  void updateStatus(AccountStatus status, {String? reason}) {
    _currentStatus = status;
    _statusCtrl.add(status);
  }

  void dispose() {
    _statusCtrl.close();
  }

  static SipKitAccount create({
    required String id,
    required SipKitAccountConfig config,
    required SipEngine engine,
  }) =>
      SipKitAccount._(id: id, config: config, engine: engine);
}
